### **Посмотрим на встроенный метод отбора признаков. И далее посмотрим на методы обертки.**

In [3]:
import pandas as pd

_Считаем данные._

In [9]:
x = pd.read_csv('../5. Обобщающая способность/Практика с кик старта/X.csv').drop('Название', axis=1)
y = pd.read_csv('../5. Обобщающая способность/Практика с кик старта/Y.csv')
x.head()

,Категория,Цель в долларах,Срок,Год публикации,Close_brent,CAD,CHF,DKK,EUR,GBP,...,Design,Fashion,Film & Video,Food,Journalism,Music,Photography,Publishing,Technology,Theater
0,6035.989239,1000.0,39,2009,34.41,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,3591.033473,80000.0,87,2009,34.41,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,3661.424550,20.0,8,2009,34.41,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,4321.245721,99.0,79,2009,34.41,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,6035.989239,1900.0,28,2009,34.41,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

_Используем лассо-регрессию. Чем больше значение alpha, тем больше признаков исчезнет._

In [10]:
from sklearn.linear_model import Lasso
#обучим
model = Lasso(alpha=15)
model.fit(x, y)
#увидим, что некоторые признаки обнулились
model.coef_

array([ 9.93083586e-01,  4.60570540e-04,  8.55846991e+01,  8.77649620e+02,
       -0.00000000e+00,  3.74721961e+02,  8.31411882e+03,  1.14150255e+02,
        3.89922933e+02,  2.71804813e+03, -1.44511540e+03, -0.00000000e+00,
       -3.80743241e+03, -6.64461691e+02, -1.92925039e+02,  1.83114376e+03,
       -6.63399901e+02,  6.96004559e+03,  0.00000000e+00, -3.75881952e+02,
       -4.85063239e+02, -1.74359657e+02, -1.53565580e+02, -1.87396020e+02,
        6.09684355e+01, -6.10636802e+02, -2.91938873e+02, -1.66925578e+02,
        2.86923530e+02, -2.53881524e+02, -1.26664721e+02,  3.26583904e+02])

### **Методы обертки.**

_Метод прямого отбора. Сначала берем один лучший признак, потом другой._

In [11]:
x.shape

(331675, 32)

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

from sklearn.feature_selection import SequentialFeatureSelector
#direction='forward' - прямой
sfs = SequentialFeatureSelector(model, n_features_to_select=5, direction='forward')
sfs.fit(x, y)

SequentialFeatureSelector(estimator=LinearRegression(), n_features_to_select=5)

_Узнаем, какие признаки мы взяли, а какие нет._

In [15]:
sfs.get_support() #булевый список
sfs.get_feature_names_out() #названия
x[sfs.get_feature_names_out()]

           Категория  Год публикации    GBP    MXN    USD
0        6035.989239            2009  False  False   True
1        3591.033473            2009  False  False   True
2        3661.424550            2009  False  False   True
3        4321.245721            2009  False  False   True
4        6035.989239            2009  False  False   True
...              ...             ...    ...    ...    ...
331670   7635.064778            2017  False  False  False
331671  38415.722876            2017   True  False  False
331672   6098.303122            2017  False  False   True
331673  38415.722876            2017  False  False   True
331674   1313.020012            2017  False  False  False

[331675 rows x 5 columns]

_Метод обратного отбора. Смотрим, какой один признак выбросить._

In [17]:
model = LinearRegression()

from sklearn.feature_selection import SequentialFeatureSelector
#direction='backward' - обратный
sfs = SequentialFeatureSelector(model, n_features_to_select=30, direction='backward')
sfs.fit(x, y)

KeyboardInterrupt:

_Увидим эти признаки._

In [ ]:
sfs.get_support() #булевый список
sfs.get_feature_names_out() #названия
x[sfs.get_feature_names_out()]