In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.6'

In [4]:
data = pd.read_csv('car_fuel_efficiency_2026.csv')
data.shape
data.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
data['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [6]:
data.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
np.max(data['fuel_efficiency_mpg'])

np.float64(41.2)

**Вопрос 6.**

Заполним пропущенные значения.

In [8]:
#nanmedian - считает медианное значение
#не учитывая пропуски
np.nanmedian(data['horsepower']) #сейчас значение 254.0

#найдем значение, которое встречается чаще всего
data['horsepower'].value_counts()

#заполним пропуски самым частым значением 252.0
data['horsepower'] = data['horsepower'].fillna(252)

#узнаем изменилось ли оно
np.median(data['horsepower'])
#оно уменьшилось

np.float64(252.0)

**Вопрос 7.**
Найдем веса линейной модели.

In [12]:
#только из Азии
mask = data['origin'] == 'Asia'
#создадим y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
#создадим x
x = data.loc[mask, ['vehicle_weight', 'model_year']].iloc[:7]
x.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

Проведем вычисление весов.

In [13]:
x = x.to_numpy()

xtx = x.T @ x
xtx_inv = np.linalg.inv(xtx)
w = xtx_inv @ x.T @ y
print(sum(w))

0.36919696904925486